Update azure-pipelines-3.yml for Azure Pipelines

diff --git a/azure-pipelines-3.yml b/azure-pipelines-3.yml
--- a/azure-pipelines-3.yml
+++ b/azure-pipelines-3.yml
@@ -34,6 +34,21 @@ stages:
     pool:
       name : 'local'
     steps:
+        
+    - task: UsePythonVersion@0
+      inputs:
+        versionSpec: '3.x'
+        addToPath: true
+    - script: |
+        if ! command -v az &> /dev/null
+        then
+          echo "Azure CLI could not be found, installing..."
+          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
+        else
+          echo "Azure CLI is already installed"
+        fi
+      displayName: 'Install Azure CLI if not already installed'
+    
     - task: AzureKeyVault@2
       inputs:
         azureSubscription: 'Azure subscription 1(0c3061a0-6c31-4710-9a05-1f1925e07805)'
